---
title: "day_2"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
#install.packages("zoo")
library(zoo)
#install.packages('plotly')
library(plotly)
#install.packages('gapminder')
library(gapminder)
install.packages('runner')
library(runner)


#read in
xword_raw1 <- read.csv("/Volumes/GoogleDrive/My Drive/data_stuff/data_stories/nyt.crossword/nyt.crossword/mini_xword_current.csv")

#fix time format and date format, get identifier for day of the week
xword_raw <- xword_raw1 %>%
  separate(Time, c("min", "sec"), sep = ":", rem = F)

xword_raw <- xword_raw %>%
  mutate(
    time_og = Time,
    min_sec = as.numeric(min)*60,
    sec = as.numeric(sec),
    duration = min_sec + sec,
    date =mdy(Date),
    day = wday(date)
  ) %>%
  filter(date <= today())

xword <- xword_raw %>%
  select(date,time_og,duration,day)


```

```{r}


xword_speed <- xword %>%
  mutate(weekday = recode(day, 
      "1" = "Sunday",
      "2" = "Monday",
      "3" = "Tuesday",
      "4" = "Wendesday",
      "5" = "Thursday",
      "6" = "Friday",
      "7" = "Saturday"),
      month = as.yearmon(date)
)

xword_speed$weekday <- factor(xword_speed$weekday, levels = c("Sunday", "Monday", "Tuesday", "Wendesday", "Thursday", "Friday", "Saturday"))

xword_speed_chart <- xword_speed %>%
  transmute(date= date,
         sun = case_when(day == 1 ~ duration),
         mon = case_when(day == 2 ~ duration),
         tue = case_when(day == 3 ~ duration),
         wed = case_when(day == 4 ~ duration),
         thur = case_when(day == 5 ~ duration),
         fri = case_when(day == 6 ~ duration),
         sat = case_when(day == 7 ~ duration),
         day,
         weekday
  ) %>%
  mutate (
    sunavg = runner(x = xword_speed_chart$sun, f = function(x) {
    mean( tail(x[!is.na(x)],7))
      } ),
    monavg = runner(x = xword_speed_chart$mon, f = function(x) {
    mean( tail(x[!is.na(x)],7))
      } )
  )
    
```


```{r}
updatemenus_avg <- list(
  list(
    active = -1,
    type= 'buttons',
    buttons = list(
      list(
        label = "Sun",
        method = "update",
        args = list(list(visible = c(TRUE, TRUE,FALSE,FALSE)))),
      list(
        label = "Mon",
        method = "update",
        args = list(list(visible = c(FALSE, FALSE,TRUE,TRUE))))
)))

fig_avg <- plot_ly(xword_speed_chart,type = 'scatter') %>%
        add_trace(xword_speed_chart, x=~date, y=~xword_speed_chart$sun, name="Sun", mode = 'markers') %>%
        add_trace(xword_speed_chart, x=~date, y=~xword_speed_chart$sunavg, name="Sun Avg", mode = 'line' ) %>%
        add_trace(xword_speed_chart, x=~date, y=~xword_speed_chart$mon, name="Mon", mode = 'markers') %>%
        add_trace(xword_speed_chart, x=~date, y=~xword_speed_chart$monavg, name="Mon Avg", mode = 'line' ) %>%
  
  layout(title = "Weekday", showlegend=FALSE,
         xaxis=list(title="Date"),
         yaxis=list(title="Duration (Sec)"),
         updatemenus=updatemenus_avg)
fig_avg

```


```{r}
updatemenus <- list(
  list(
    active = -1,
    type= 'buttons',
    buttons = list(
      list(
        label = "Sun",
        method = "update",
        args = list(list(visible = c(TRUE, FALSE,FALSE,FALSE,FALSE,FALSE,FALSE)))),
      list(
        label = "Mon",
        method = "update",
        args = list(list(visible = c(FALSE, TRUE,FALSE,FALSE,FALSE,FALSE,FALSE)))),
      list(
        label = "Tue",
        method = "update",
        args = list(list(visible = c(FALSE, FALSE,TRUE,FALSE,FALSE,FALSE,FALSE)))),
      list(
        label = "Wed",
        method = "update",
        args = list(list(visible = c(FALSE, FALSE,FALSE,TRUE,FALSE,FALSE,FALSE)))),
      list(
        label = "Thur",
        method = "update",
        args = list(list(visible = c(FALSE, FALSE,FALSE,FALSE,TRUE,FALSE,FALSE)))),
      list(
        label = "Fiday",
        method = "update",
        args = list(list(visible = c(FALSE, FALSE,FALSE,FALSE,FALSE,TRUE,FALSE)))),
      list(
        label = "Sat",
        method = "update",
        args = list(list(visible = c(FALSE, FALSE,FALSE,FALSE,FALSE,FALSE,TRUE))))
    )))


fig <- plot_ly(xword_speed_chart,type = 'scatter', mode = 'lines+markers') 
fig <- fig %>% add_trace(xword_speed_chart, x=~date, y=~xword_speed_chart$sun, name="Sun") %>%
               add_trace(xword_speed_chart, x=~date, y=~xword_speed_chart$sun, name="Sun") %>%
fig <- fig %>% add_trace(xword_speed_chart, x=~date, y=~xword_speed_chart$mon, name="Mon") 
fig <- fig %>% add_trace(xword_speed_chart, x=~date, y=~xword_speed_chart$tue, name="Tue") 
fig <- fig %>% add_trace(xword_speed_chart, x=~date, y=~xword_speed_chart$wed, name="Wed") 
fig <- fig %>% add_trace(xword_speed_chart, x=~date, y=~xword_speed_chart$thur, name="Thur")
fig <- fig %>% add_trace(xword_speed_chart, x=~date, y=~xword_speed_chart$fri, name="Fri") 
fig <- fig %>% add_trace(xword_speed_chart, x=~date, y=~xword_speed_chart$sat, name="Sat") %>% 
  layout(title = "Weekday", showlegend=FALSE,
         xaxis=list(title="Date"),
         yaxis=list(title="Duration (Sec)"),
         updatemenus=updatemenus)

fig


```



